(() => {
  const $ = s => document.querySelector(s);
  if (!document.body.classList.contains('demo-page')) {
    const lang = new URLSearchParams(location.search).get('lang') === 'en' ? 'en' : 'zh';
    document.querySelectorAll('a[href]').forEach(a => { const h=a.getAttribute('href'); if(h&&!h.startsWith('#')&&!h.startsWith('http')) a.href=h+(h.includes('?')?'&':'?')+'lang='+lang; });
    const b=$('#language-toggle'); b.textContent='EN'; b.onclick=()=>location.search='?lang=en'; return;
  }
  const intent=$('#intent-text'), badge=$('#gesture-badge'), message=$('#camera-message');
  const status=t=>intent.textContent=t;
  (async()=>{
    let THREE,OrbitControls,GLTFLoader;
    try { THREE=await import('https://esm.sh/three@0.180.0'); ({OrbitControls}=await import('https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js')); ({GLTFLoader}=await import('https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js')); } catch(e){$('#loading').textContent='3D 资源加载失败';return;}
    const host=$('#three'),viewer=$('#viewer'),labels=$('#part-labels'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,host.clientWidth/host.clientHeight,.1,100),renderer=new THREE.WebGLRenderer({antialias:true});
    scene.background=new THREE.Color(0x202223);camera.position.set(10.8,6.1,12.4);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;host.append(renderer.domElement);
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=20;controls.target.set(.4,.2,0);
    const light=(type,color,p,pos)=>{const l=new type(color,p);l.position.set(...pos);scene.add(l);return l};light(THREE.HemisphereLight,0xe8eef0,1.8,[0,4,0]);const key=light(THREE.DirectionalLight,0xfff5e7,4.5,[6,10,8]);key.castShadow=true;key.shadow.mapSize.set(2048,2048);light(THREE.DirectionalLight,0xc9dce4,2.1,[-7,4,5]);light(THREE.DirectionalLight,0xa9c5d4,3.2,[-4,7,-8]);
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0x333536,roughness:.42,metalness:.25}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.82;floor.receiveShadow=true;scene.add(floor);
    const product=new THREE.Group();product.rotation.y=-.26;scene.add(product);const m=(color,rough=.35,metal=.7)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal}),iron=m(0x343a3d,.42),paint=m(0x245365,.3),steel=m(0xa7afb1,.2,1),black=m(0x111416,.58,.28),copper=m(0x8e5c3d,.35,.8),registry=[],hits=[];
    const G=()=>{const g=new THREE.Group();product.add(g);return g},add=(g,geo,mat,p=[0,0,0],r=[0,0,0])=>{const x=new THREE.Mesh(geo,mat);x.position.set(...p);x.rotation.set(...r);x.castShadow=x.receiveShadow=true;g.add(x);return x},reg=(id,label,description,node,a,e,delay)=>{node.position.set(...a);node.traverse(x=>{if(x.isMesh){x.userData.id=id;hits.push(x)}});const tag=document.createElement('span');tag.className='part-label';tag.textContent=label;labels.append(tag);registry.push({id,label,description,node,a:new THREE.Vector3(...a),e:new THREE.Vector3(...e),delay,tag})},bolts=(g,r,x,n=8)=>{for(let i=0;i<n;i++){let a=i/n*Math.PI*2;add(g,new THREE.CylinderGeometry(.09,.09,.13,12),steel,[x,Math.cos(a)*r,Math.sin(a)*r],[0,0,Math.PI/2])}};
    let base=G();add(base,new THREE.BoxGeometry(8.8,.32,2.9),black,[0,-1.34,0]);[-3.5,3.5].forEach(x=>{add(base,new THREE.BoxGeometry(.28,.44,3.15),iron,[x,-1.08,0]);[-1.05,1.05].forEach(z=>add(base,new THREE.CylinderGeometry(.2,.2,.1,16),steel,[x,-1.57,z]))});reg('base','铸铁底座','承载整机并保证联轴器装配同轴度。',base,[0,0,0],[0,-.42,0],0);
    let motor=G();add(motor,new THREE.CylinderGeometry(1.18,1.18,3.25,48),paint,[0,0,0],[0,0,Math.PI/2]);[-1.18,-.88,-.58,-.28,.02,.32,.62,.92,1.22].forEach(x=>add(motor,new THREE.TorusGeometry(1.21,.045,10,44),black,[x,0,0],[0,Math.PI/2,0]));[-1.72,1.72].forEach(x=>add(motor,new THREE.CylinderGeometry(1.27,1.27,.23,48),iron,[x,0,0],[0,0,Math.PI/2]));add(motor,new THREE.BoxGeometry(1.35,.55,.9),iron,[-.2,1.22,0]);reg('motor','高效永磁电机','驱动核心转子；散热筋与接线盒为示意结构。',motor,[-2.55,0,0],[-5.1,.1,0],.12);
    let bearing=G();add(bearing,new THREE.CylinderGeometry(.72,.72,.5,36),iron,[0,0,0],[0,0,Math.PI/2]);add(bearing,new THREE.CylinderGeometry(.48,.48,.64,36),black,[0,0,0],[0,0,Math.PI/2]);bolts(bearing,.58,.28,6);reg('bearing','轴承座组件','支撑传动轴并维持旋转组件稳定定位。',bearing,[-.55,0,0],[-1.25,.55,0],.28);
    let coupling=G();[-.35,.35].forEach(x=>add(coupling,new THREE.CylinderGeometry(.43,.43,.34,28),steel,[x,0,0],[0,0,Math.PI/2]));add(coupling,new THREE.CylinderGeometry(.38,.38,.38,28),black,[0,0,0],[0,0,Math.PI/2]);reg('coupling','弹性联轴器','补偿装配偏差并降低传动振动。',coupling,[1.05,0,0],[.5,1.22,0],.4);
    let shaft=G();add(shaft,new THREE.CylinderGeometry(.21,.21,3.5,28),steel,[0,0,0],[0,0,Math.PI/2]);reg('shaft','拉丝钢传动轴','将电机扭矩传递至叶轮。',shaft,[2.7,0,0],[2.7,.75,0],.54);
    let seal=G();add(seal,new THREE.CylinderGeometry(.55,.55,.36,36),black,[0,0,0],[0,0,Math.PI/2]);add(seal,new THREE.TorusGeometry(.48,.08,10,36),steel,[0,0,0],[0,Math.PI/2,0]);reg('seal','机械密封组件','降低泄漏风险，便于维护更换。',seal,[3.18,0,0],[3.1,1.15,0],.64);
    let impeller=G();add(impeller,new THREE.CylinderGeometry(1.02,1.02,.44,42),copper,[0,0,0],[0,0,Math.PI/2]);for(let i=0;i<7;i++)add(impeller,new THREE.BoxGeometry(.75,.1,.28),steel,[0,.35,0],[i*Math.PI/3.5,.32,0]);reg('impeller','高性能叶轮','示意叶轮用于说明流道与扬程效率。',impeller,[3.83,0,0],[4.6,.4,0],.76);
    let housing=G();add(housing,new THREE.CylinderGeometry(1.68,1.68,.82,56),paint,[0,0,0],[0,0,Math.PI/2]);add(housing,new THREE.TorusGeometry(1.36,.18,14,56),iron,[0,0,0],[0,Math.PI/2,0]);add(housing,new THREE.CylinderGeometry(.73,.73,1.1,36),iron,[.35,1.4,0]);add(housing,new THREE.CylinderGeometry(.73,.73,1.1,36),iron,[-.9,0,1.35],[Math.PI/2,0,0]);bolts(housing,1.35,.48,10);reg('housing','离心泵壳体','铸造泵体与法兰接口构成流道外壳。',housing,[4.65,0,0],[6.45,.05,0],.9);
    let cover=G();add(cover,new THREE.CylinderGeometry(1.72,1.72,.18,56),iron,[0,0,0],[0,0,Math.PI/2]);bolts(cover,1.38,.14,10);reg('cover','泵盖与法兰','泵盖可拆卸，用于内部组件维护检查。',cover,[5.16,0,0],[8.05,0,0],1.05);
    let loaded=false;try{let r=await fetch('assets/industrial-pump.glb',{method:'HEAD'});if(r.ok){let gltf=await new GLTFLoader().loadAsync('assets/industrial-pump.glb');product.clear();product.add(gltf.scene);gltf.scene.scale.setScalar(1.6);loaded=true;status('已加载本地 GLB 工业模型')}}catch{}$('#loading').classList.add('is-hidden');
    let explosion=0,target=0;const hero=new THREE.Vector3(10.8,6.1,12.4),wide=new THREE.Vector3(14.2,7.2,16.7),focus=new THREE.Vector3(.4,.2,0),wideFocus=new THREE.Vector3(1.2,.2,0);
    const show=c=>{$('#part-title').textContent=c.label;$('#part-description').textContent=c.description;$('#part-card').classList.add('show')},explode=()=>{target=1;viewer.classList.add('exploded');$('#mode-text').textContent='分层爆炸视图';status('识别到张开手掌 → 逐层展开装配组件')},assemble=()=>{target=0;viewer.classList.remove('exploded');$('#part-card').classList.remove('show');$('#value-card').classList.remove('show');$('#mode-text').textContent='整机展示';status('识别到握拳 → 按装配顺序自动回装')};$('#close-part').onclick=()=>$('#part-card').classList.remove('show');$('#close-value').onclick=()=>$('#value-card').classList.remove('show');
    const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointermove',e=>{let b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);let h=ray.intersectObjects(hits)[0];renderer.domElement.style.cursor=h?'pointer':'grab';if(h&&explosion>.8)show(registry.find(c=>c.id===h.object.userData.id))});renderer.domElement.addEventListener('click',e=>{if(explosion>.8)renderer.domElement.dispatchEvent(new PointerEvent('pointermove',{clientX:e.clientX,clientY:e.clientY}))});
    (function loop(){requestAnimationFrame(loop);controls.update();explosion=THREE.MathUtils.lerp(explosion,target,.038);if(!loaded)registry.forEach(c=>{let t=THREE.MathUtils.smoothstep((explosion-c.delay)/.42,0,1);c.node.position.lerpVectors(c.a,c.e,t);let p=c.node.getWorldPosition(new THREE.Vector3()).project(camera);c.tag.style.left=(p.x*.5+.5)*viewer.clientWidth+'px';c.tag.style.top=(-p.y*.5+.5)*viewer.clientHeight+'px'});if(!loaded){impeller.rotation.x+=.018;shaft.rotation.x+=.012}camera.position.lerpVectors(hero,wide,explosion);controls.target.lerpVectors(focus,wideFocus,explosion);renderer.render(scene,camera)})();
    addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)});
    let recognizer,stream,running=false,last=-1,active='',start=0,cool=0,lastX=null,lastPinch=null;const video=$('#video'),canvas=$('#hand-canvas'),ctx=canvas.getContext('2d'),links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
    const draw=p=>{canvas.width=video.videoWidth;canvas.height=video.videoHeight;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.lineWidth=2;ctx.strokeStyle='rgba(209,229,237,.9)';links.forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(p[a].x*canvas.width,p[a].y*canvas.height);ctx.lineTo(p[b].x*canvas.width,p[b].y*canvas.height);ctx.stroke()})};
    async function model(){if(recognizer)return;badge.textContent='正在加载 MediaPipe…';let {GestureRecognizer,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/+esm'),v=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');recognizer=await GestureRecognizer.createFromOptions(v,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-tasks/gesture_recognizer/gesture_recognizer.task'},runningMode:'VIDEO',numHands:1});badge.textContent='视觉模型已就绪'}
    function run(){if(!running)return;if(video.readyState>=2&&video.currentTime!==last){last=video.currentTime;let r=recognizer.recognizeForVideo(video,performance.now());if(r.landmarks?.length){let p=r.landmarks[0];draw(p);if(lastX!==null)product.rotation.y-=(p[9].x-lastX)*3.6;lastX=p[9].x;let pin=Math.hypot(p[4].x-p[8].x,p[4].y-p[8].y);if(lastPinch!==null)product.scale.setScalar(THREE.MathUtils.clamp(product.scale.x+(pin-lastPinch)*3.5,.75,1.35));lastPinch=pin;if(r.gestures?.length){let g=r.gestures[0][0],n=performance.now();badge.textContent=g.categoryName+' '+Math.round(g.score*100)+'%';if(g.score>.55){if(g.categoryName!==active){active=g.categoryName;start=n}else if(n-start>300&&n-cool>850){cool=n;if(active==='Open_Palm')explode();if(active==='Closed_Fist')assemble();if(active==='Thumb_Up'){$('#value-card').classList.add('show');status('识别到点赞 → 展示 POC 业务价值')}}}}}}requestAnimationFrame(run)}
    $('#camera-btn').onclick=async e=>{let b=e.currentTarget;b.disabled=true;try{await model();stream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480}});video.srcObject=stream;await video.play();running=true;b.textContent='视觉识别运行中';message.textContent='摄像头已启用，手势可控制产品。';run()}catch(err){console.warn(err);badge.textContent='视觉识别不可用';message.textContent='无法启动摄像头或加载视觉模型；3D 静态体验仍可使用。';message.classList.add('error');b.disabled=false;b.textContent='重试视觉识别'}};addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));
  })();
})();
