const media={demoVideo:'assets/project-demo.mp4',heroScreenshot:'assets/screens/project-main.png',screenshots:[{title:'AI 问答',src:'assets/screens/ai-chat.png'},{title:'错题讲解',src:'assets/screens/wrong-question.png'},{title:'学习建议',src:'assets/screens/learning-suggestion.png'}]};
const flow=[['学生提交错题','学生请求进入学习系统'],['身份校验','JWT 权限校验'],['学习快照','Java Student Snapshot'],['课程知识检索','pgvector · 课程知识'],['AI 编排','LangGraph'],['模型生成','Qwen'],['保存运行记录','Run / Usage · PostgreSQL'],['返回讲解','解析 · 思路 · 知识点']];
const metric=(v,l)=>`<div><b>${v}</b><span>${l}</span></div>`;const check=(src,ok,no)=>{const x=new Image();x.onload=()=>ok(src);x.onerror=no;x.src=src};
function mediaRender(){document.querySelectorAll('[data-media]').forEach(n=>{const src=media[n.dataset.media];if(n.dataset.media==='demoVideo'){fetch(src,{method:'HEAD'}).then(r=>r.ok?r:Promise.reject()).then(()=>n.innerHTML=`<video controls playsinline poster="assets/screens/project-main.png"><source src="${src}" type="video/mp4"></video>`).catch(()=>{});}else check(src,p=>n.innerHTML=`<img src="${p}" alt="AI 智学平台项目核心页面截图">`,()=>{});});const c=document.querySelector('#screenshots');media.screenshots.forEach(i=>{const f=document.createElement('figure');f.className='screen-shot';f.innerHTML=`<div class="media shot-media"><div class="media-placeholder"><b>${i.title}</b><span>待补充真实项目截图</span></div></div><figcaption>${i.title}</figcaption>`;c.append(f);check(i.src,p=>f.querySelector('.media').innerHTML=`<img src="${p}" alt="${i.title}真实项目截图">`,()=>{});});}
const evidence=[['身份权限','✓',1],['学习上下文','✓',2],['知识来源','3',3],['真实模型','✓',5],['运行记录','✓',6]];
function flowRender(){const l=document.querySelector('#workflow-steps');l.innerHTML=flow.map((x,i)=>`<li class="workflow-node node-${i+1}" data-step="${i}"><span class="workflow-number">${i+1}</span><div><b>${x[0]}</b><small>${x[1]}</small></div><i class="workflow-check" aria-hidden="true">✓</i></li>`).join('');document.querySelector('#workflow-evidence').innerHTML=evidence.map((x,i)=>`<li data-evidence="${i}"><span>${x[0]}</span><b>·</b></li>`).join('');}
const workflow={timers:[],frame:0,stage:0,visible:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const clearWorkflow=()=>{workflow.timers.forEach(clearTimeout);workflow.timers=[];cancelAnimationFrame(workflow.frame);};
function anchor(a,b,box){const r=a.getBoundingClientRect(),t=b.getBoundingClientRect(),dx=t.left-r.left,dy=t.top-r.top;if(Math.abs(dx)>Math.abs(dy)){return dx>0?[r.right-box.left,r.top+r.height/2-box.top]:[r.left-box.left,r.top+r.height/2-box.top];}return dy>0?[r.left+r.width/2-box.left,r.bottom-box.top]:[r.left+r.width/2-box.left,r.top-box.top];}
function drawWorkflowLinks(){const host=document.querySelector('#workflow-flow'),svg=document.querySelector('#workflow-links'),tracks=svg.querySelector('.workflow-link-tracks'),nodes=[...document.querySelectorAll('.workflow-node')],box=host.getBoundingClientRect();if(!box.width)return;svg.setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);svg.setAttribute('width',box.width);svg.setAttribute('height',box.height);tracks.replaceChildren(...nodes.slice(0,-1).map((node,i)=>{const next=nodes[i+1],from=anchor(node,next,box),to=anchor(next,node,box),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.dataset.link=i;path.setAttribute('d',`M ${from[0]} ${from[1]} L ${to[0]} ${to[1]}`);return path;}));}
function updateEvidence(stage,done=false){document.querySelectorAll('#workflow-evidence li').forEach((item,i)=>{const active=done||stage>=evidence[i][2];item.classList.toggle('is-verified',active);item.querySelector('b').textContent=active?evidence[i][1]:'·';});const note=document.querySelector('#workflow-note');note.textContent=done?'全链路验证通过':'验证项会随着请求推进逐步更新。';note.classList.toggle('is-complete',done);}
function animateDot(linkIndex){const path=document.querySelector(`[data-link="${linkIndex}"]`),dot=document.querySelector('.workflow-link-dot');if(!path)return;document.querySelectorAll('.workflow-link-tracks path').forEach((p,i)=>p.classList.toggle('is-active',i===linkIndex));const length=path.getTotalLength(),start=performance.now(),duration=400;dot.classList.add('is-moving');const move=now=>{const point=path.getPointAtLength(length*Math.min(1,(now-start)/duration));dot.setAttribute('cx',point.x);dot.setAttribute('cy',point.y);if(now-start<duration)workflow.frame=requestAnimationFrame(move);else dot.classList.remove('is-moving');};workflow.frame=requestAnimationFrame(move);}
function setWorkflowStage(stage){workflow.stage=stage;const nodes=[...document.querySelectorAll('.workflow-node')];nodes.forEach((node,i)=>{node.classList.toggle('is-active',i===stage);node.classList.toggle('is-complete',i<stage);});updateEvidence(stage);if(stage>0)animateDot(stage-1);}
function showWorkflowComplete(){workflow.stage=8;document.querySelectorAll('.workflow-node').forEach(node=>{node.classList.remove('is-active');node.classList.add('is-complete');});document.querySelectorAll('.workflow-link-tracks path').forEach(path=>path.classList.add('is-active'));updateEvidence(8,true);}
function resetWorkflow(){document.querySelector('#workflow-flow').classList.add('is-resetting');workflow.timers.push(setTimeout(()=>{document.querySelector('#workflow-flow').classList.remove('is-resetting');startWorkflow();},600));}
function startWorkflow(){clearWorkflow();document.querySelector('#workflow-flow').classList.remove('is-resetting');if(workflow.reduced){showWorkflowComplete();return;}document.querySelectorAll('.workflow-node').forEach(node=>node.classList.remove('is-active','is-complete'));document.querySelectorAll('.workflow-link-tracks path').forEach(path=>path.classList.remove('is-active'));updateEvidence(-1);const schedule=[500,2500,4500,6500,9000,11500,14000,16500];schedule.forEach((at,stage)=>workflow.timers.push(setTimeout(()=>setWorkflowStage(stage),at)));workflow.timers.push(setTimeout(showWorkflowComplete,18500),setTimeout(resetWorkflow,22000));}
fetch('evidence/case-evidence.json').then(r=>r.ok?r.json():Promise.reject()).then(d=>{document.querySelector('#hero-metrics').innerHTML=[metric(d.goldenSet,'已批准 Golden Set'),metric(`${d.recallAt5*100}%`,'Recall@5'),metric(`${d.coreE2E.passed}/${d.coreE2E.total}`,'核心业务 E2E'),metric(d.pythonTests,'Python Tests')].join('');document.querySelector('#rag-pipeline').innerHTML=[[d.documents,'真实授权课程文档'],[d.chunks,'知识切片'],['Gemini Embedding','1024D'],['pgvector','向量检索'],[d.goldenSet,'Approved Golden Set']].map(x=>`<li><b>${x[0]}</b><span>${x[1]}</span></li>`).join('');document.querySelector('#rag-metrics').innerHTML=[metric(`${d.recallAt5*100}%`,'Recall@5'),metric(`${d.sourceHitRate*100}%`,'Source Hit'),metric(`${d.citationValidity*100}%`,'Citation Validity'),metric(d.mrr.toFixed(3),'MRR')].join('');document.querySelector('#gate-numbers').innerHTML=[metric(d.pythonTests,'Python Tests'),metric(d.goldenSet,'RAG Evaluation'),metric(`${d.coreE2E.passed} / ${d.coreE2E.total}`,'Core E2E')].join('');}).catch(()=>document.querySelectorAll('#hero-metrics,#rag-metrics,#gate-numbers').forEach(x=>x.textContent='验证汇总暂不可用。'));
mediaRender();flowRender();drawWorkflowLinks();new ResizeObserver(drawWorkflowLinks).observe(document.querySelector('#workflow-flow'));document.addEventListener('visibilitychange',()=>{workflow.visible=!document.hidden;if(workflow.visible)startWorkflow();else clearWorkflow();});window.addEventListener('pagehide',clearWorkflow,{once:true});document.querySelector('#replay-workflow').onclick=startWorkflow;startWorkflow();
